//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated using Tobago MDA.
//     Model           : <Tobago.ProjectName>
//     Template        : Table Gateway Custom.tpl
//     Runtime Version : $Version$
//     Generation date : <Tobago.CurrentDate>
//
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using Adf.Base.Data;
using Adf.Base.Query;
using Adf.Core.Data;

namespace $Class.Model$.Data
{
	/// <summary>
	/// Gateway class for $Class.Name$ based on the Table Gateway Pattern
	/// </summary>
	public static partial class $Class.Name.Pascal$Gateway
	{
		
	}
}
