//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Model           : <Tobago.ProjectName>
//     Template        : View Model.tpl
//     Runtime Version : $Version$
//     Generation date : <Tobago.CurrentDate>
//
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Adf.Base.ViewModels;
using $Class.Model$.Business;

namespace $Class.Model$.Process.ViewModels
{
    public class $Class.Name.Pascal$ViewModel : ViewModel<$Class.Name.Pascal$>
    {
        public $Class.Name.Pascal$ViewModel($Class.Name.Pascal$ $Class.Name.Camel$) : base($Class.Name.Camel$)
        {
        }
	}
}
