//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Model           : <Tobago.ProjectName>
//     Template        : Business Object Entity.tpl
//     Runtime Version : $Version$
//     Generation date : <Tobago.CurrentDate>
//
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using $Class.Model$.Data;
using Adf.Core;
using Adf.Business;
using Adf.Business.Validation;
using Adf.Business.SmartReferences;
using Adf.Data;
using Adf.Business.ValueObject;

namespace $Class.Model$.Business
{
	/// <summary>
	/// DomainObject $Class.Name$
	/// </summary>
	public partial class $Class.Name.Pascal$ : DomainObject
	{
        #region CodeGuard(Constructors)

        internal $Class.Name.Pascal$()
        {
            state = NullInternalState.Null;
        }

        internal $Class.Name.Pascal$(IInternalState newstate)
        {
            state = newstate;
        }
	
        #endregion CodeGuard(Constructors)
        
        #region CodeGuard(Empty)

        private static readonly $Class.Name.Pascal$ empty = new $Class.Name.Pascal$();
	    
	    public static $Class.Name.Pascal$ Empty
	    {
	        get
	        {
	            return empty;
	        }
        }

        #endregion CodeGuard(Empty)
        
        #region CodeGuard(Property Id)

        public override ID Id
        {
            get { return state.GetValue<ID>($Class.Name.Pascal$Describer.Id); }
        }

        #endregion CodeGuard(Property Id)

<Tobago.Loop(Class.Attributes, Attributes)>
<Tobago.Loop(Class.NavigableAssociations, Associations)>

		#region CodeGuard(Custom)
		
		#endregion CodeGuard(Custom)
	}
}