//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Model           : <Tobago.ProjectName>
//     Template        : Enumeration.tpl
//     Runtime Version : $Version$
//     Generation date : <Tobago.CurrentDate>
//
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel;


namespace $Class.Model$.Business
{
	public enum $Class.Name.Pascal$
	{
		[Description("")] Empty,
<Tobago.Loop(Class.Attributes, Attributes)>		
	}
}
