//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Model           : <Tobago.ProjectName>
//     Template        : Tasks.tpl
//     Runtime Version : $Version$
//     Generation date : <Tobago.CurrentDate>
//
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Adf.Core.Tasks;

namespace $Model.Name.Pascal$.Process
{
	public class $Model.Name.Pascal$Task : ApplicationTask
	{
		public $Model.Name.Pascal$Task(string name) : base(name) {}

<Tobago.Loop(Model.UseCases, Properties)>
	}
}