//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated using Tobago MDA.
//     Model           : <Tobago.ProjectName>
//     Template        : Table Gateway.tpl
//     Runtime Version : $Version$
//     Generation date : <Tobago.CurrentDate>
//
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Adf.Core;
using Adf.Data;
using Adf.Data.Database;
using Adf.Data.Query;

namespace $Class.Model$.Data
{
	/// <summary>
	/// Report gateway class for $Class.Name$ based on the Report Gateway Pattern
	/// </summary>
	public partial class $Class.Name.Pascal$Gateway : TableGateway
	{
		private static readonly DataSources DataSource = $Class.Name.Pascal$Describer.Table.DataSource;
		
		public static IInternalState[] GetAll()
		{
			IQuery query = DataSourceManager.GetQuery(DataSource);

			query.Execute($Class.Name.Pascal$Describer.Table);

			return DataSourceManager.RunAndSplit(query);
		}
	}
}
