//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adf.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adf.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script language=&apos;javascript&apos;&gt;
        ///// Check only date keys are pressed (0-9) or -
        ///// use in onkeypress event
        ///function date_keys() 
        ///{
        ///    var intCode;
        ///    
        ///    intCode = window.event.keyCode;
        ///    if ( (intCode &lt; &quot;0&quot;.charCodeAt(0)) || (intCode &gt; &quot;9&quot;.charCodeAt(0)) )
        ///    {
        ///		if (intCode != &quot;-&quot;.charCodeAt(0))
        ///		{
        ///			window.event.cancelBubble = true;
        ///			window.event.returnValue = false;
        ///		}  
        ///    }
        ///}
        ///
        ///// Check only date&amp;time keys are pressed (0-9) or - or :
        ///// use in onkeypress event
        ///function dat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot;&gt;
        ///
        ///function ShowInfoButton(e) {
        ///    var evt = e || window.event;
        ///    var element = evt.target || evt.srcElement;
        ///    var InfoButton = document.getElementById(&quot;InfoButton&quot;);
        ///
        ///    if (InfoButton != null)
        ///    {
        ///        InfoButton.innerHTML = element.InfoText;
        ///
        ///        var left = (document.body.clientWidth - InfoButton.clientWidth) / 2;
        ///        InfoButton.style.left = left + &quot;px&quot;;
        ///        
        ///        var top = (document.body.clientHeight - InfoButton.clientHeight) / 2;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InfoButtonScript {
            get {
                return ResourceManager.GetString("InfoButtonScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot;&gt;InitInfoTip();&lt;/script&gt;.
        /// </summary>
        internal static string InitInfoButton {
            get {
                return ResourceManager.GetString("InitInfoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function MetaBuilders_RowSelectorColumn_SelectAll( parentCheckBox ) {
        ///    if ( typeof( document.getElementById ) == &quot;undefined&quot; ) return;
        ///    if ( parentCheckBox == null || typeof( parentCheckBox.participants ) == &quot;undefined&quot; ) {
        ///        return;
        ///    }
        ///    var participants = parentCheckBox.participants;
        ///    for ( var i=0; i &lt; participants.length; i++ ) {
        ///        var participant = participants[i];
        ///        if ( participant != null ) {
        ///            participant.checked = parentCheckBox.checked;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rowselectorcolumn {
            get {
                return ResourceManager.GetString("rowselectorcolumn", resourceCulture);
            }
        }
    }
}
