//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Model           : <Tobago.ProjectName>
//     Template        : Descriptor.tpl
//     Runtime Version : $Version$
//     Generation date : <Tobago.CurrentDate>
//
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace $Class.Model$.Business
{
	/// <summary>
	/// Summary description for desriptor $Class.Name$. A descriptor is a type that acts like an enum,
	/// but, other than an enum, can be specialised.
	/// </summary>
	public class $Class.Name$ : Descriptor
	{
		public $Class.Name$() {}
		public $Class.Name$(string n) : base(n) {}

<Tobago.Loop(Class.Attributes, Attributes)>

		#region CodeGuard(Custom)

		#endregion CodeGuard(Custom)
	}
}