//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Model           : <Tobago.ProjectName>
//     Template        : Window Panel.tpl
//     Runtime Version : $Version$
//     Generation date : <Tobago.CurrentDate>
//
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Adf.Win;

namespace $Class.Model$.Win.Panels
{
	public class Panel$Class.Name$ : <Tobago.Marking("Default Panel Style", "HorizontalPanel")>
	{

		protected override void SetLines()
		{
			base.SetLines();

<Tobago.Loop(Class.Attributes, Attributes)>

<Tobago.Loop(Class.Associations, Associations)>	
            
			#region CodeGuard(Custom)
	
			#endregion CodeGuard(Custom)
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		private void InitializeComponent()
		{
			this.SuspendLayout();
			// 
			// PanelBook
			// 
			this.Name = "$Class.Name$";
			this.ResumeLayout(false);
			this.PerformLayout();

		}				
	}
}