//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Tobago MDA.
//     Model           : <Tobago.ProjectName>
//     Template        : Search Object.tpl
//     Runtime Version : $Version$
//     Generation date : <Tobago.CurrentDate>
//
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Adf.Base.Domain;
using Adf.Business;
using Adf.Business.Search;
using Adf.Business.ValueObject;
using Adf.Business.SmartReferences;

namespace $Class.Model$.Business
{
    public class $Class.Name.Pascal$SearchObject : SearchObject
    {
<Tobago.Loop(Class.Attributes, Attributes)>
<Tobago.Loop(Class.NavigableAssociations, Associations)>
    }
}
