//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Model           : <Tobago.ProjectName>
//     Template        : Value Object.tpl
//     Runtime Version : $Version$
//     Generation date : <Tobago.CurrentDate>
//
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Text.RegularExpressions;
using Adf.Core.Domain;

namespace Adf.Business.ValueObject 
{
    public struct $Class.Name$ : IValueObject, IEquatable<$Class.Name$>, IComparable, IComparable<$Class.Name$>
    {
        private string value;
        public object Value
        {
            get { return value; }
        }

        public override string ToString()
        {
            return string.IsNullOrEmpty(value) ? string.Empty : value;
        }

        #region CodeGuard(Expression)
        
        private static Regex Expression = new Regex(@"");

        #endregion CodeGuard(Expression)
        
        public $Class.Name$(string s)
        {
            //initialize
            value = null;

            if (string.IsNullOrEmpty(s)) return;

            if (!IsValid$Class.Name$(s))
            {
                throw new FormatException(String.Format("Value {0} is not a valid $Class.Name.Lower$", s));
            }

            value = s;            
        }

        #region Validity

        #region CodeGuard(IsValid)
        
        /// <summary>
        /// Checks whether a value is a valid $Class.Name.Lower$.
        /// </summary>
        /// <param name="s">Name to try</param>
        /// <returns>true f parameter is a valid $Class.Name.Lower$</returns>
        public static bool IsValid$Class.Name$(string s)
        {
            return Expression.IsMatch(s);
        }

        #endregion CodeGuard(IsValid)

        /// <summary>
        /// Checks whether the value presented is a valid $Class.Name.Lower$.
        /// </summary>
        /// <param name="s">The string that is validated to see if it contains a valid <see cref="$Class.Name$"/>.</param>
        /// <param name="result">The resulting $Class.Name.Lower$, or the $Class.Name$.Empty if the string did not contain a valid <see cref="$Class.Name$"/>.</param>
        /// <returns>
        /// A <see cref="$Class.Name$"></see> containing a fully qualified type name.
        /// </returns>
        public static bool TryParse(string s, out $Class.Name$ result)
        {
            result = Empty;

            if (string.IsNullOrEmpty(s))
            {
                return true;
            }

            if (!IsValid$Class.Name$(s))
            {
                return false;
            }

            result = new $Class.Name$(s);
            return true;
        }

		public static bool TryParse(string s, IFormatProvider provider, out $Class.Name$ result)
        {
            return TryParse(s, out result);
        }

        #endregion

        #region Empty

        public static $Class.Name$ Empty
        {
            get { return new $Class.Name$(string.Empty); }
        }

        /// <summary>
        /// Gets a value indicating whether this instance is empty.
        /// </summary>
        /// <value><c>true</c> if this instance is empty; otherwise, <c>false</c>.</value>
        public bool IsEmpty
        {
            get { return string.IsNullOrEmpty(value); }
        }

        #endregion Empty

        #region Equality

        /// <summary>
        /// Identifies if the internal value of the parameter is equal to this object's internal value.
        /// </summary>
        /// <param name="other">$Class.Name.Lower$</param>
        /// <returns></returns>
        public bool Equals($Class.Name$ other)
        {
            return value.Equals(other.value);
        }

        /// <summary>
        /// Compares this instance to another <see cref="$Class.Name$"/> object.
        /// </summary>
        /// <param name="obj">The <see cref="$Class.Name$"/> object to compare against.</param>
        /// <returns>
        /// <c>true</c> if both $Class.Name.Lower$s are the same; otherwise <c>false</c>
        /// </returns>
        public override bool Equals(object obj)
        {
            if (obj == null)
                return false;

            if (obj is $Class.Name$)
                return Equals(($Class.Name$) obj);

            return false;
        }

        public override int GetHashCode()
        {
            return value.GetHashCode();
        }

        /// <summary>
        /// Returns the equality of two <see cref="$Class.Name$"/> objects.
        /// </summary>
        /// <param name="i">The first <see cref="$Class.Name$"/>.</param>
        /// <param name="j">The second <see cref="$Class.Name$"/>.</param>
        /// <returns>
        /// <c>true</c> if both $Class.Name.Lower$s are the same; otherwise <c>false</c>
        /// </returns>
        public static bool operator ==($Class.Name$ i, $Class.Name$ j)
        {
            return i.Equals(j);
        }
        
        /// <summary>
        /// Returns the inequality of two <see cref="$Class.Name$"/> objects.
        /// </summary>
        /// <param name="i">The first <see cref="$Class.Name$"/>.</param>
        /// <param name="j">The second <see cref="$Class.Name$"/>.</param>
        /// <returns>
        /// <c>true</c> if the $Class.Name.Lower$s are different; otherwise <c>false</c>
        /// </returns>
        public static bool operator !=($Class.Name$ i, $Class.Name$ j)
        {
            return !i.Equals(j);
        }

        #endregion Equality

        #region Comparison

        ///<summary>
        ///Compares the current instance with another object of the same type.
        ///</summary>
        ///
        ///<returns>
        ///A 32-bit signed integer that indicates the relative order of the objects being compared. The return value has these meanings: Value Meaning Less than zero This instance is less than obj. Zero This instance is equal to obj. Greater than zero This instance is greater than obj. 
        ///</returns>
        ///
        ///<param name="obj">An object to compare with this instance. </param>
        ///<exception cref="T:System.ArgumentException">obj is not the same type as this instance. </exception><filterpriority>2</filterpriority>
        public int CompareTo(object obj)
        {
            if (obj == null)
                return 1;

            if (!(obj is $Class.Name$)) 
                throw new ArgumentException("Object is not a $Class.Name.Lower$");

            $Class.Name$ other = ($Class.Name$) obj;

            return value.CompareTo(other.value);
        }

        ///<summary>
        ///Compares the current object with another object of the same type.
        ///</summary>
        ///
        ///<returns>
        ///A 32-bit signed integer that indicates the relative order of the objects being compared. The return value has the following meanings: Value Meaning Less than zero This object is less than the other parameter.Zero This object is equal to other. Greater than zero This object is greater than other. 
        ///</returns>
        ///
        ///<param name="other">An object to compare with this object.</param>
        public int CompareTo($Class.Name$ other)
        {
            return value.CompareTo(other.value);
        }

        #endregion

        #region CodeGuard(Custom)

        #endregion CodeGuard(Custom)
    }
}
