//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Model           : <Tobago.ProjectName>
//     Template        : Reference Types.tpl
//     Runtime Version : $Version$
//     Generation date : <Tobago.CurrentDate>
//
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Adf.Business.SmartReferences;

namespace $Model.Name$.Business
{
	/// <summary>
	/// Contains all constants for smart references in $Model.Name$.
	/// </summary>
	public class ApplicationReferences : References
	{
		public ApplicationReferences() {}
		public ApplicationReferences(string n) : base(n) {}

<Tobago.Loop(Model.Classes, Classes)>	}

<Tobago.Loop(Model.Classes, Classes SmartReference)>
}
