//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Model           : SmartReferences
//     Template        : Business Describer.tpl
//     Runtime Version : $Version$
//     Generation date : 26-9-2007 13:43:38
//
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Adf.Core.Data;

namespace Adf.Data.SmartReferences
{
    /// <summary>
    /// Represents the describer for business layer mapping with data layer.
    /// It contains definitions for business class SmartReference and its providers.
    /// </summary>
    public sealed class SmartReferenceDescriber : BusinessDescriber
    {
        #region Constructor

        /// <summary>
        /// Initializes a new instance of the <see cref="Adf.Data.SmartReferences.SmartReferenceDescriber"/> class with no arguments.
        /// </summary>
        private SmartReferenceDescriber()
        {
            //hide constructor
        }

        #endregion

        #region CodeGuard(Private fields)

        /// <summary>
        /// Represents the SmartReference table.
        /// </summary>
        private static readonly TableDescriber table = new TableDescriber("SmartReference", SmartReferenceSources.SmartReference);

        /// <summary>
        /// Represents the ID column of SmartReference table.
        /// </summary>
        private static readonly ColumnDescriber id = new ColumnDescriber("Id", Table);

        /// <summary>
        /// Represents the Name column of SmartReference table.
        /// </summary>
        private static readonly ColumnDescriber name = new ColumnDescriber("Name", Table);

        /// <summary>
        /// Represents the Description column of SmartReference table.
        /// </summary>
        private static readonly ColumnDescriber description = new ColumnDescriber("Description", Table);

        /// <summary>
        /// Represents the IsDefault column of SmartReference table.
        /// </summary>
        private static readonly ColumnDescriber isdefault = new ColumnDescriber("IsDefault", Table);

        /// <summary>
        /// Represents the BeginDate column of SmartReference table
        /// </summary>
        private static readonly ColumnDescriber begindate = new ColumnDescriber("BeginDate", Table);

        /// <summary>
        /// Represents the EndDate column of SmartReference table
        /// </summary>
        private static readonly ColumnDescriber enddate = new ColumnDescriber("EndDate", Table);

        /// <summary>
        /// Represents the Type column of SmartReference table.
        /// </summary>
        private static readonly ColumnDescriber type = new ColumnDescriber("Type", Table);


        #endregion CodeGuard(Private fields)

        #region CodeGuard(Properties)

        /// <summary>
        /// Gets the database table name.
        /// </summary>
        /// <returns>The database table SmartReference.</returns>
        public static TableDescriber Table
        {
            get { return table; }
        }

        /// <summary>
        /// Gets the Id column of SmartReference table.
        /// </summary>
        /// <returns>The Id column of SmartReference table.</returns>
        public static ColumnDescriber Id
        {
            get { return id; }
        }

        /// <summary>
        /// Gets the Name column of SmartReference table.
        /// </summary>
        /// <returns>The Name column of SmartReference table.</returns>
        public static ColumnDescriber Name
        {
            get { return name; }
        }

        /// <summary>
        /// Gets the Description column of SmartReference table.
        /// </summary>
        /// <returns>The Description column of SmartReference table.</returns>
        public static ColumnDescriber Description
        {
            get { return description; }
        }

        /// <summary>
        /// Gets the IsDefault column of SmartReference table.
        /// </summary>
        /// <returns>The IsDefault column of SmartReference table.</returns>
        public static ColumnDescriber IsDefault
        {
            get { return isdefault; }
        }

        /// <summary>
        /// Gets the BeginDate column of SmartReference table.
        /// </summary>
        /// <returns>The BeginDate column of SmartReference table.</returns>
        public static ColumnDescriber BeginDate
        {
            get { return begindate; }
        }

        /// <summary>
        /// Gets the EndDate column of SmartReference table.
        /// </summary>
        /// <returns>The EndDate column of SmartReference table.</returns>
        public static ColumnDescriber EndDate
        {
            get { return enddate; }
        }

        /// <summary>
        /// Gets the Type column of SmartReference table.
        /// </summary>
        /// <returns>The Type column of SmartReference table.</returns>
        public static ColumnDescriber Type
        {
            get { return type; }
        }

        #endregion CodeGuard(Properties)
    }
}
