//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Model           : <Tobago.ProjectName>
//     Template        : Business Describer.tpl
//     Runtime Version : $Version$
//     Generation date : <Tobago.CurrentDate>
//
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Adf.Core.Data;

namespace $Class.Model$.Data
{
    /// <summary>
    /// $Class.Name$Describer contains definitions for business class $Class.Name$ and its providers.
    /// </summary>
    public sealed class $Class.Name.Pascal$Describer : BusinessDescriber
    {
		// Avoids instantiation by hiding public base constructor
        private $Class.Name.Pascal$Describer() {}

        public static readonly ITable Table = new TableDescriber("$Class.Name.Pascal$", ApplicationDataSources.Application);
        
        public static readonly IColumn Id = new ColumnDescriber("Id", Table);
<Tobago.Loop(Class.Attributes, Attributes)>
<Tobago.Loop(Class.NavigableAssociations, Associations)>
    }
}
