//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Model           : <Tobago.ProjectName>
//     Template        : Business Object Entity.tpl
//     Runtime Version : $Version$
//     Generation date : <Tobago.CurrentDate>
//
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Adf.Base.Domain;
using Adf.Business;
using Adf.Business.ValueObject;
using Adf.Business.SmartReferences;
using Adf.Core.Extensions;
using $Class.Model$.Business;

namespace $Class.Model$.Test.Mocks
{
	/// <summary>
	/// Mock Domain Object Factory $Class.Name$
	/// </summary>
	public static class $Class.Name.Pascal$MockFactory 
	{
		private static DomainCollection<$Class.Name.Pascal$> _$Class.Name.Camel.Plural$;
        public static DomainCollection<$Class.Name.Pascal$> GetAll()
        {
            return _$Class.Name.Camel.Plural$ ?? (_$Class.Name.Camel.Plural$ = $Class.Name.Pascal$Factory.GetAll());
        }

//		public static $Class.Name.Pascal$ PickOne()
//        {
//            return GetAll().PickOne();
//        }
	
        public static $Class.Name.Pascal$ Create()
        {
			var $Class.Name.Camel$  = $Class.Name.Pascal$Factory.New();

<Tobago.Loop(Class.Attributes, Attributes)>
<Tobago.Loop(Class.NavigableAssociations, Associations)>
			return $Class.Name.Camel$;
		}
	}
}
