//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Model           : <Tobago.ProjectName>
//     Template        : Task.tpl
//     Runtime Version : $Version$
//     Generation date : <Tobago.CurrentDate>
//
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Adf.Base.Domain;
using Adf.Base.Tasks;
using Adf.Business.Search;
using Adf.Core;
using Adf.Business;
using Adf.Core.Tasks;
using Adf.Core.Validation;
using $UseCase.Model.Name.Pascal$.Business;

namespace $UseCase.Model.Name.Pascal$.Process
{

	public class $UseCase.Name.Pascal$Task : Task
	{
		public $UseCase.Name.Pascal$Task(ApplicationTask name, ITask origin) : base(name, origin) {}        

<Tobago.Loop(UseCase.Attributes, "Members")>
<Tobago.Loop(UseCase.Attributes, "Properties")>
	
		#region CodeGuard(Start)

		public override void Start(params object[] p)
        {
<Tobago.Loop(UseCase.Attributes, "Start")>

			this.ActivateView();
		}
		
		#endregion CodeGuard(Start)	


		#region CodeGuard(Continue)
		
		public override void Continue(ApplicationTask finishedtask, TaskResult returns, params object[] p)
        {
<Tobago.Loop(UseCase.Attributes, "Continue")>

			this.ActivateView();
		}

		#endregion CodeGuard(Continue)
		

		#region CodeGuard(Actions)

<Tobago.Loop(UseCase.Attributes, "Actions")>
		#endregion CodeGuard(Actions)
	
	
		#region CodeGuard(Custom)

		#endregion CodeGuard(Custom)
	
	}		
}
