<?xml version="1.0" encoding="utf-8" ?>
<!--
<auto-generated>
    This code was generated by a tool.
    Model           : <Tobago.ProjectName>
    Template        : Business Describer.tpl
    Runtime Version : $Version$
    Generation date : <Tobago.CurrentDate>
	
    Changes to this file may cause incorrect behavior and may be lost if
    the code is regenerated.

	Make sure that the .hbm.xml files are compiled into the assembly as Embedded Resources.

</auto-generated>
-->
<hibernate-mapping xmlns="urn:nhibernate-mapping-2.0">
	<class name="$Class.Model.Name.Camel.Trim$.Business.$Class.Name$, $Class.Model.Name.Camel.Trim$.Business" table="$Class.Name$" lazy="true">
		<id name="ID" column="ID" type="Adf.Data.NHibernate.IdGuidType, Adf.Data.NHibernate">
			<generator class="assigned"/>
		</id>
<Tobago.Loop(Class.Attributes, Attributes)>
<Tobago.Loop(Class.Associations, Associations)>
	</class>
</hibernate-mapping>