-- ------------------------------------------------------------------------------
-- <auto-generated>
--     This code was generated by a tool.
--     Model           : <Tobago.ProjectName>
--     Template        : Table Create.tpl
--     Runtime Version : $Version$
--     Generation date : <Tobago.CurrentDate>
--
--     Changes to this file may cause incorrect behavior and may be lost if
--     the code is regenerated.
-- </auto-generated>
-- ------------------------------------------------------------------------------

<Tobago.Loop(Class.Attributes, Attributes)>

<Tobago.Loop(Class.NavigableAssociations, Relations)>