//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated using Tobago MDA.
//     Model           : <Tobago.ProjectName>
//     Template        : Business Object Factory Custom.tpl
//     Runtime Version : $Version$
//     Generation date : <Tobago.CurrentDate>
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Diagnostics.CodeAnalysis;
using Adf.Core;
using Adf.Business;
using Adf.Data;
using $Class.Model$.Data;

namespace $Class.Model$.Business
{
	/// <summary>
	/// $Class.Name$ Factory, used to instantiate $Class.Name$ classes
	/// </summary>
	public partial class $Class.Name.Pascal$Factory
	{
		
	}
}
