//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Model           : <Tobago.ProjectName>
//     Template        : Business Object Entity.tpl
//     Runtime Version : $Version$
//     Generation date : <Tobago.CurrentDate>
//
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Adf.Base.Data;
using Adf.Base.Domain;
using Adf.Business;
using Adf.Base.Validation;
using Adf.Business.SmartReferences;
using Adf.Business.ValueObject;
using Adf.Core.Data;
using Adf.Core.Identity;
using $Class.Model$.Data;

namespace $Class.Model$.Business
{
	/// <summary>
	/// DomainObject $Class.Name$
	/// </summary>
	public partial class $Class.Name.Pascal$ : DomainObject
	{
        #region CodeGuard(Constructors)

        internal $Class.Name.Pascal$()
        {
            state = NullInternalState.Null;
        }

        internal $Class.Name.Pascal$(IInternalState newstate)
        {
            state = newstate;
        }
	
        #endregion CodeGuard(Constructors)
          
        #region CodeGuard(Property Id)

		private ID _id;
        public override ID Id
        {
            get { return _id.IsEmpty ? (_id = state.Get<ID>($Class.Name.Pascal$Describer.Id)) : _id; }
        }

        #endregion CodeGuard(Property Id)

<Tobago.Loop(Class.Attributes, Attributes)>
<Tobago.Loop(Class.NavigableAssociations, Associations)>
<Tobago.Loop(Class.Operations, Operations)>

		#region CodeGuard(Custom)
		
		#endregion CodeGuard(Custom)
	}
}
