//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Model           : <Tobago.ProjectName>
//     Template        : Smart Panel - Search.tpl
//     Runtime Version : $Version$
//     Generation date : <Tobago.CurrentDate>
//
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Web.UI.WebControls;
using Adf.Web.UI;
using $Class.Model$.Business;

namespace $Class.Model$.Web.Panels
{
	public class SearchPanel$Class.Name.Pascal$ : SmartPanel
	{
		protected override void OnInit(EventArgs e)
		{
			base.OnInit(e);
			
<Tobago.Loop(Class.Attributes, Attributes)>
			//Blank();
<Tobago.Loop(Class.NavigableAssociations, Associations)>			
			#region CodeGuard(Custom)
	
			#endregion CodeGuard(Custom)
		}		
	}
}
